apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:  #replicaset labels
    project: roboshop
    tier: database
    component: mongodb
 
spec:
  replicas: 1
  selector: #Selector it uses replica set labels ( using this labels replicaset selects the pod)
    matchLabels:
      project: roboshop
      tier: database
      component: mongodb
# This is pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: mongodb
      containers:
        - name: mongodb
          image: dock944/mongodb:1.0.0
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb          # Name of the Service  
spec:
  selector:  #labels are used as selectors
    project: roboshop
    tier: database
    component: mongodb                # Matches Pods with these labels
    
  ports:
    - name: http
      protocol: TCP           # Protocol (TCP/UDP/SCTP)
      port: 27017               # Port exposed by the Service
      targetPort: 27017      #container




